# Generated by Django 6.0.5 on 2026-06-01 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hazard_type', models.CharField(choices=[('FLOOD', 'Flood'), ('TYPHOON', 'Typhoon'), ('LANDSLIDE', 'Landslide'), ('EARTHQUAKE', 'Earthquake'), ('FIRE', 'Fire'), ('STORM_SURGE', 'Storm Surge')], max_length=20)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('OFFLINE', 'Offline')], default='NORMAL', max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('municipality', models.CharField(max_length=100)),
                ('last_reading', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, help_text='e.g. mm, m/s, magnitude', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('hazard_type', models.CharField(choices=[('FLOOD', 'Flood'), ('TYPHOON', 'Typhoon'), ('LANDSLIDE', 'Landslide'), ('EARTHQUAKE', 'Earthquake'), ('FIRE', 'Fire'), ('STORM_SURGE', 'Storm Surge')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MONITORING', 'Monitoring'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=15)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MODERATE', max_length=10)),
                ('municipality', models.CharField(max_length=100)),
                ('location_details', models.TextField(help_text='Street, barangay, landmarks')),
                ('affected_population', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='incidents.hazardsensor')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_bulk_update', 'Can bulk update incident status'), ('can_view_all', 'Can view all incidents')],
            },
        ),
        migrations.CreateModel(
            name='HazardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hazard_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='incidents.incident')),
            ],
        ),
        migrations.CreateModel(
            name='EarlyWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_level', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('DANGER', 'Danger'), ('CRITICAL', 'Critical')], default='WARNING', max_length=10)),
                ('municipality', models.CharField(blank=True, help_text='Leave blank for all municipalities', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
