# Generated by Django 6.0.5 on 2026-06-02 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacuationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('municipality', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('current_occupancy', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('CLOSED', 'Closed'), ('STANDBY', 'On Standby')], default='STANDBY', max_length=10)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['municipality', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AlertLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(choices=[('FLOOD', 'Flood'), ('TYPHOON', 'Typhoon'), ('LANDSLIDE', 'Landslide'), ('EARTHQUAKE', 'Earthquake'), ('FIRE', 'Fire'), ('STORM_SURGE', 'Storm Surge')], max_length=20)),
                ('level', models.CharField(choices=[('GREEN', 'Green — Normal'), ('YELLOW', 'Yellow — Advisory'), ('ORANGE', 'Orange — Warning'), ('RED', 'Red — Danger')], default='GREEN', max_length=10)),
                ('municipality', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CitizenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('FLOOD', 'Flood'), ('FIRE', 'Fire'), ('LANDSLIDE', 'Landslide'), ('DAMAGE', 'Structural Damage'), ('RESCUE', 'Rescue Needed'), ('ROAD', 'Road Blocked'), ('OTHER', 'Other')], max_length=15)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('municipality', models.CharField(max_length=100)),
                ('barangay', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='citizen_reports/')),
                ('reporter_name', models.CharField(max_length=100)),
                ('reporter_contact', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Validation'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizen_reports', to='incidents.incident')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('VEHICLE', 'Rescue Vehicle'), ('MEDICAL', 'Medical Supply'), ('FOOD', 'Food & Water'), ('RESCUE_TEAM', 'Rescue Team'), ('EQUIPMENT', 'Equipment'), ('SHELTER', 'Shelter Supply')], max_length=15)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(blank=True, help_text='e.g. units, kg, liters', max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('DEPLOYED', 'Deployed'), ('MAINTENANCE', 'Under Maintenance'), ('EXHAUSTED', 'Exhausted')], default='AVAILABLE', max_length=15)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('municipality', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='incidents.incident')),
                ('managed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['resource_type', 'name'],
            },
        ),
    ]
