# Generated by Django 6.0.5 on 2026-06-03 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_evacuationcenter_alertlevel_citizenreport_resource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=200)),
                ('municipality', models.CharField(max_length=100)),
                ('temperature', models.FloatField(blank=True, help_text='°C', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='%', null=True)),
                ('rainfall_1h', models.FloatField(blank=True, help_text='mm/hr', null=True)),
                ('rainfall_24h', models.FloatField(blank=True, help_text='mm/24hr', null=True)),
                ('wind_speed', models.FloatField(blank=True, help_text='km/h', null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=10)),
                ('river_level', models.FloatField(blank=True, help_text='meters', null=True)),
                ('condition', models.CharField(choices=[('CLEAR', 'Clear'), ('CLOUDY', 'Cloudy'), ('RAINY', 'Rainy'), ('STORMY', 'Stormy'), ('TYPHOON', 'Typhoon')], default='CLEAR', max_length=10)),
                ('pagasa_advisory', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(choices=[('PAGASA', 'PAGASA'), ('PHIVOLCS', 'PHIVOLCS'), ('NDRRMC', 'NDRRMC'), ('LDRRMO', 'LDRRMO'), ('OTHER', 'Other Agency')], max_length=10)),
                ('bulletin_type', models.CharField(choices=[('ADVISORY', 'Advisory'), ('WATCH', 'Watch'), ('WARNING', 'Warning'), ('BULLETIN', 'Bulletin'), ('FORECAST', 'Forecast')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='DamageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_type', models.CharField(choices=[('HOUSE', 'House/Structure'), ('ROAD', 'Road/Bridge'), ('FARM', 'Agricultural'), ('INFRA', 'Infrastructure'), ('LIVELIHOOD', 'Livelihood')], max_length=15)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('MAJOR', 'Major'), ('TOTAL', 'Total Loss')], max_length=10)),
                ('location', models.TextField()),
                ('municipality', models.CharField(max_length=100)),
                ('barangay', models.CharField(blank=True, max_length=100)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('affected_families', models.PositiveIntegerField(default=0)),
                ('affected_persons', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='damage_assessments/')),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_assessments', to='incidents.incident')),
            ],
            options={
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='HazardMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('zone_type', models.CharField(choices=[('FLOOD', 'Flood Zone'), ('LANDSLIDE', 'Landslide Zone'), ('STORM_SURGE', 'Storm Surge Zone'), ('EARTHQUAKE', 'Earthquake Fault Zone'), ('TSUNAMI', 'Tsunami Zone'), ('FIRE', 'Fire-Prone Zone')], max_length=15)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MODERATE', 'Moderate Risk'), ('HIGH', 'High Risk'), ('VERY_HIGH', 'Very High Risk')], max_length=10)),
                ('municipality', models.CharField(max_length=100)),
                ('barangay', models.CharField(blank=True, max_length=100)),
                ('affected_population', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-risk_level', 'municipality'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
