# Generated by Django 6.0.5 on 2026-06-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_incident_latitude_incident_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='incident_images/'),
        ),
    ]
