# Generated by Django 6.0.5 on 2026-06-03 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
