# Generated by Django 6.0.5 on 2026-06-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardimage',
            name='image',
            field=models.ImageField(upload_to='hazards/'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='image',
            field=models.ImageField(default='', upload_to='hazards/'),
            preserve_default=False,
        ),
    ]
