# Generated by Django 6.0.5 on 2026-06-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_alter_hazardimage_image_alter_incident_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hazards/'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hazards/'),
        ),
    ]
